# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/FPGA_EGR680/counter_verilog/counter_verilog.cache/wt [current_project]
set_property parent.project_path C:/FPGA_EGR680/counter_verilog/counter_verilog.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA_EGR680/counter_verilog/counter_verilog.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/FPGA_EGR680/counter_verilog/counter_verilog.srcs/sources_1/new/counter_verilog.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA_EGR680/counter_verilog/counter_verilog.srcs/constrs_1/new/counter_pins.xdc
set_property used_in_implementation false [get_files C:/FPGA_EGR680/counter_verilog/counter_verilog.srcs/constrs_1/new/counter_pins.xdc]


synth_design -top counter_verilog -part xc7z020clg400-1


write_checkpoint -force -noxdef counter_verilog.dcp

catch { report_utilization -file counter_verilog_utilization_synth.rpt -pb counter_verilog_utilization_synth.pb }
