
# coding: utf-8

# ## LED Ctrl
# 
# Use buttons and sliders to control the LEDs on the board.
# 
# The program is started by select Menubar -> Cell -> Run All
# 
# Cell -> Current Outputs -> Toggle Scrolling
#    

# In[1]:


import time
from pynq.overlays.base import BaseOverlay

import ipywidgets as widgets
from IPython.display import display



# ### Load overlay bitstream file generated by Vivado

# In[2]:


base = BaseOverlay("base.bit")


# ### Variables

# In[3]:


button0 = widgets.Button(description="LD0", button_style='primary')
button1 = widgets.Button(description="LD1", button_style='success')
button2 = widgets.Button(description="LD2", button_style='danger')
button3 = widgets.Button(description="LD3", button_style='warning')

ldStatus0 = widgets.Label(value='False')
ldStatus1 = widgets.Label(value='False')
ldStatus2 = widgets.Label(value='False')
ldStatus3 = widgets.Label(value='False')



# ### Define functions here
# Function decision() provides the computaion of the win and loss with average and a consol ouput accordingly.
# #### Colors RGB LED No 4 and 5
#     off = 0    blue = 1    green = 2    türkies = 3    red = 4    purple = 5    yellow = 6
#     white = 7
# 

# In[4]:


def on_button0_clicked(b):
    base.leds[0].toggle()
    ldStatus0.value = '' + ('False' if base.leds.read() & int('0001',2) == 0 else 'True')
def on_button1_clicked(b):
    base.leds[1].toggle()
    ldStatus1.value = '' + ('False' if base.leds.read() & int('0010',2) == 0 else 'True')
def on_button2_clicked(b):
    base.leds[2].toggle()
    ldStatus2.value = '' + ('False' if base.leds.read() & int('0100',2) == 0 else 'True')
def on_button3_clicked(b):
    base.leds[3].toggle()
    ldStatus3.value = '' + ('False' if base.leds.read() & int('1000',2) == 0 else 'True')
def handle_slider0_change(change):
    base.rgbleds[4].write(change.new)
def handle_slider1_change(change):
    base.rgbleds[5].write(change.new)


# ### Start progarm

# In[5]:


button0.on_click(on_button0_clicked)
button1.on_click(on_button1_clicked)
button2.on_click(on_button2_clicked)
button3.on_click(on_button3_clicked)

slider0 = widgets.IntSlider(min=0, max=7, value=0, description='RGB_1')
slider1 = widgets.IntSlider(min=0, max=7, value=0, description='RGB_2')

slider0.observe(handle_slider0_change, names='value')
slider1.observe(handle_slider1_change, names='value')

# turn all led's off
for led in base.leds:
    led.off()    

    
display(button0)
display(ldStatus0)
display(button1)
display(ldStatus1)
display(button2)
display(ldStatus2)
display(button3)
display(ldStatus3)
display(slider0, slider1)

