# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/FPGA_EGR680/time_multiplexed/time_multiplexed.cache/wt [current_project]
set_property parent.project_path C:/FPGA_EGR680/time_multiplexed/time_multiplexed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA_EGR680/time_multiplexed/time_multiplexed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/FPGA_EGR680/time_multiplexed/time_multiplexed.srcs/sources_1/new/clk_divider.v
  C:/FPGA_EGR680/time_multiplexed/time_multiplexed.srcs/sources_1/new/decoder.v
  C:/FPGA_EGR680/time_multiplexed/time_multiplexed.srcs/sources_1/new/time_multiplexed_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA_EGR680/time_multiplexed/time_multiplexed.srcs/constrs_1/new/time_multiplexed_pins.xdc
set_property used_in_implementation false [get_files C:/FPGA_EGR680/time_multiplexed/time_multiplexed.srcs/constrs_1/new/time_multiplexed_pins.xdc]


synth_design -top time_multiplexed_top -part xc7z020clg400-1


write_checkpoint -force -noxdef time_multiplexed_top.dcp

catch { report_utilization -file time_multiplexed_top_utilization_synth.rpt -pb time_multiplexed_top_utilization_synth.pb }
